### ISSUE TITLE
macOS 11 Symbol not found: _NSLocalizedDescriptionKey

### ISSUE THREAD

**Issue by u3dreal** [media2x/rife-ncnn-vulkan-python#3]
Hello and thank you for this nice port to python !

when i try to execute rife_ncnn_vulkan.py ( with pics added to images folder ) 
I get the following error.
`Traceback (most recent call last):
  File "/Users/drquader/Desktop/RIFE_python/rife-ncnn-vulkan-python-20210504-macos/rife_ncnn_vulkan.py", line 12, in <module>
    import rife_ncnn_vulkan_wrapper as raw
  File "/Users/drquader/Desktop/RIFE_python/rife-ncnn-vulkan-python-20210504-macos/rife_ncnn_vulkan_wrapper.py", line 15, in <module>
    import _rife_ncnn_vulkan_wrapper
ImportError: dlopen(/Users/drquader/Desktop/RIFE_python/rife-ncnn-vulkan-python-20210504-macos/_rife_ncnn_vulkan_wrapper.so, 2): Symbol not found: _NSLocalizedDescriptionKey
  Referenced from: /Users/drquader/Desktop/RIFE_python/rife-ncnn-vulkan-python-20210504-macos/_rife_ncnn_vulkan_wrapper.so
  Expected in: flat namespace
 in /Users/drquader/Desktop/RIFE_python/rife-ncnn-vulkan-python-20210504-macos/_rife_ncnn_vulkan_wrapper.so`

this usually means it is not linked agains Foundation Framework. Any idea ?

Thanks alot !

**Comment by ArchieMeng** [comment]
Emmm, I don't have a mac, so I don't know what it means.
Could you try using the git version and install as python package through the setuptools way (python setup.py install).

I guess there might be some errors in the CMakeList.txt since it changed a lot during the times. Another reason might be the python lib linking is broken just like [ImportError: DLL load failed while importing _rife_ncnn_vulkan_wrapper: The specified module could not be found.](https://github.com/media2x/rife-ncnn-vulkan-python/issues/1) or [What does "Symbol not found / Expected in: flat namespace" actually mean?](https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean). If that is the case, then a static link on your device might help. Change CMakeList.txt's python part on the tail like [https://github.com/media2x/rife-ncnn-vulkan-python/blob/6c84631b9b43368471840868e0a67ad704815750/src/CMakeLists.txt#L296-L298](https://github.com/media2x/rife-ncnn-vulkan-python/blob/6c84631b9b43368471840868e0a67ad704815750/src/CMakeLists.txt#L296-L298) might solve the issue.

Additionally, could you check:
- if the latest git version works
- if rife-ncnn-vulkan (nihui's original one) release build works
- What are exactly linked with _rife_ncnn_vulkan_wrapper.so on OSX? Maybe [this link from StackOverFlow](https://stackoverflow.com/questions/4506121/how-to-print-a-list-of-symbols-exported-from-a-dynamic-library) may help.

**Comment by k4yt3x** [comment]
I think this line is for compiling the original CLI binary only, not for the linked library we're trying to build. @ArchieMeng's confirmation is required here, though.

P.S. enclose your multi-line code block with ```s instead of single `s.

**Comment by u3dreal** [comment]
OK but Foundation framework is needed for osx. Maybe i will do a fork.

**Comment by k4yt3x** [comment]
It'll be great if you can figure that out. Neither I or @ArchieMeng has a macOS system nor much macOS development experiences.

**Comment by ArchieMeng** [comment]
> After having a look at the CMakaList.txt i think there is something commented out that should be there ..
> 
> ```
> list(APPEND RIFE_LINK_LIBRARIES
>         ${Metal}
>         ${QuartzCore}
>         ${CoreGraphics}
>         ${Cocoa}
>         ${IOKit}
>         ${IOSurface}
>         ${Foundation}
>         ${CoreFoundation}
>     )
> endif()
> 
> #target_link_libraries(rife-ncnn-vulkan ${RIFE_LINK_LIBRARIES})
> ```
> 
> why is this commented out ?? It adds Foundation to the RIFE_LINK_LIBRARIES but it is commented out ??
> This is necessary for macos.
> 
> I do not have vulkan and SWIG installed and i would be happy to avoid it. Maybe you cam change it and let actions do the work.

Just the same as what @k4yt3x said, the commented line was used for building original binary executable.

For Foundation libs, the CMakeList.txt part of this https://github.com/media2x/rife-ncnn-vulkan-python/blob/8903d898e039e264a8b03a5d12777488a96909d2/rife_ncnn_vulkan_python/CMakeLists.txt#L225-L245

is enabled in the release action with
https://github.com/media2x/rife-ncnn-vulkan-python/blob/8903d898e039e264a8b03a5d12777488a96909d2/.github/workflows/release.yml#L192-L203
So the MacOS version should have already been linked with Foundation libs.

PS: @k4yt3x  @u3dreal , I suddenly remembered that I had a very old Macbook air. Maybe I can reopen it to try the testing, but don't expect too much on this, I am not familiar with Mac.

**Comment by u3dreal** [comment]
I forked it ... I'll have a look when i have time

**Comment by u3dreal** [comment]
Hmm strange i'm not able to compile nihui version of rife on BigSur.  Getting segfaults ..
Must be a problem with Vukan SDK and MacOSSDK versions. 
So for now i can not test it. precompiled rife from nihui works well on 11.5.

**Comment by ArchieMeng** [comment]
That's fine, because environment issues are common.
Maybe [nihui's github release action file](https://github.com/nihui/rife-ncnn-vulkan/blob/master/.github/workflows/release.yml) might help.

**Comment by u3dreal** [comment]
I followed in detail the release.yaml but no luck
